# Generated by Django 3.2.8 on 2021-10-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='img',
            field=models.ImageField(max_length=200, upload_to='static/images/', verbose_name='Изображение'),
        ),
    ]
